openapi: 3.0.1
info:
  title: Nombre Producto API - Nombre API
  version: 0.0.0
  description: >-
    Alcance funcional de toda la API. No es preciso entrar en detalles particulares de las operaciones, sino una descripcipon general del contexto funcional.
  contact:
    name: Developers Support
    email: soporteapisinternas@bank.com.co
servers:
  - url: >-
      https://$(catalog.host)/v?/bian-business-area/business-domain/service-domain/nombre-prducto-api/nombre-api
paths:
  /examplePath1:
    post: # REEMPLAZAR POR VERBO HTTP EN MINÚSCULA; get, post, put, patch. delete...
      operationId: nombreFuncionalOperacion
      x-api-type: proxy-jwt
      summary: >-
        Alcance funcional de la capacidad/operación resumido. Resaltar lo más esencial.
      description: >
        ### Clasificación de la información: Pública, Interna, Restringida, Confidencial

        Alcance funcional de la capacidad/operación adicionando detalles complementarios a lo esencial. NO debe ser igual al "summary".
      parameters:
        - name: accept
          in: header
          required: true
          schema:
            type: string
          description: application/json, el cual representa el formato de mensajería.
        - name: message-id
          in: header
          required: true
          schema:
            type: string
            pattern: >-
              ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$
          description: >-
            Identificador de transacción. Se recomienda usar un UUID para el
            valor de este campo.
          example: "c4e6bd04-5149-11e7-b114-b2f933d5fe66"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/examplePath1Request'
            examples:
              min_Required:
                description: ESCENARIO_DADO_CUANDO_ENTONCES_
                value:
                  {
                      "data": {
                          "customer": {
                              "identification": {
                                  "relationshipId": "some text"
                              },
                              "fullName": "some text"
                          }
                      }
                  }
              complete_Info:
                  description: ESCENARIO_DADO_CUANDO_ENTONCES_
                  value:
                    data:
                      customer:
                        identification:
                          relationshipId: F1E4F933826EE5FF33
                        fullName: Juan Martin Maya
        required: true
      responses:
        '200':
          x-success-response: Successfull
          description: Registro exitoso
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlacion usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
            RateLimit-Limit:
              description: Limite de solicitudes por intervalo de tiempo
              schema:
                type: number
            Content-Type:
              description: 'Formato de mensajeria de la API. Ejemplo: application/json.'
              schema:
                type: string
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/examplePath1Response'
              examples:
                minRequired:
                  value:
                    data:
                      meta:
                        _requestDateTime: '2024-01-26T14:52:09.779Z'
                        _applicationId: default
                        _messageId: dbff089d-292d-4894-b842-8e88c7003525
                      customerId: "10987734037"
        '400':
          description: Bad request
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlación usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
            RateLimit-Limit:
              description: Límite de solicitudes por intervalo de tiempo
              schema:
                type: number
            Content-Type:
              description: 'Formato de mensajería de la API. Ejemplo: application/json.'
              schema:
                type: string
                x-ibm-languages:
                  description:
                    en: 'API message format. Example: application/json.'
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
                x-ibm-languages:
                  description:
                    en: 'API Version. Example: 1.0.0.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe66
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 400
                title: Bad Resquest
                errors:
                  - code: SA404
                    detail: >-
                      La longitud de la parte entera del parametro trackingId es
                      invalida
          x-ibm-languages:
            description:
              en: Error in the request.
        '401':
          description: Credenciales incorrectas.
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlación usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
                x-ibm-languages:
                  description:
                    en: >-
                      Message identifier or correlation identifier used for the
                      traceability of the API calls.
            RateLimit-Limit:
              description: Límite de solicitudes por intervalo de tiempo
              schema:
                type: number
                x-ibm-languages:
                  description:
                    en: Resquest limit per time interval.
            Content-Type:
              description: 'Formato de mensajería de la API. Ejemplo: application/json.'
              schema:
                type: string
                x-ibm-languages:
                  description:
                    en: 'API message format. Example: application/json.'
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
                x-ibm-languages:
                  description:
                    en: 'API Version. Example: 1.0.0.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 401
                title: Unauthorized
                errors:
                  - code: SA401
                    detail: El consumidor no tiene acceso a la información solicitada
          x-ibm-languages:
            description:
              en: Incorrect credentials.
        '404':
          description: Recurso no encontrado.
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlación usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
                x-ibm-languages:
                  description:
                    en: >-
                      Message identifier or correlation identifier used for the
                      traceability of the API calls.
            RateLimit-Limit:
              description: Límite de solicitudes por intervalo de tiempo
              schema:
                type: number
                x-ibm-languages:
                  description:
                    en: Resquest limit per time interval.
            Content-Type:
              description: 'Formato de mensajería de la API. Ejemplo: application/json.'
              schema:
                type: string
                x-ibm-languages:
                  description:
                    en: 'API message format. Example: application/json.'
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
                x-ibm-languages:
                  description:
                    en: 'API Version. Example: 1.0.0.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 404
                title: Not Found
                errors:
                  - code: BP12700891
                    detail: EL CLIENTE NO TIENE CUENTAS DEL TIPO SOLICITADO
          x-ibm-languages:
            description:
              en: Resource not found.
        '409':
          description: >
            El estado del recurso presenta conflictos con los datos de la
            solicitud.
                        #Aqui se debe de poner todos los codigos de error, para la automatizacion
            Listado de códigos de error

            | code | detail |

            | --------------- | --------------- |

            | BP12700858 | EL NUMERO Y TIPO DE DOCUMENTO NO PERTENECE A UN
            CLIENTE bank O DE COMERCIO INTERNACIONAL bank |

            | BP12700871 | EL BENEFICIARIO SE ENCUENTRA EN LISTA DE CONTROL |

            | BP12700865 | ERROR EN EL REVERSO DE LA DECLARACION DE CAMBIO |
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlación usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
            RateLimit-Limit:
              description: Límite de solicitudes por intervalo de tiempo
              schema:
                type: number
            Content-Type:
              description: 'Formato de mensajería de la API. Ejemplo: application/json.'
              schema:
                type: string
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
              examples:
                example4:
                        value:
                          data:
                           meta:
                            _requestDateTime: '2024-01-26T14:52:09.779Z'
                            _applicationId: default
                            _messageId: dbff089d-292d-4894-b842-8e88c7003525
                           status: 409
                           title: Conflict
                           errors:
                            - code: BP20251
                              detail: Estado del recurso no permite la acción requerida
        '500':
          description: Error interno del servidor.
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlación usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
            RateLimit-Limit:
              description: Límite de solicitudes por intervalo de tiempo
              schema:
                type: number
            Content-Type:
              description: 'Formato de mensajería de la API. Ejemplo: application/json.'
              schema:
                type: string
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 500
                title: Internal Server Error
                errors:
                  - code: SP500
                    detail: Ha ocurrido un error interno controlado en el servidor.
        '502':
          description: Error en la respuesta del proveedor del servicio.
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlación usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
            RateLimit-Limit:
              description: Límite de solicitudes por intervalo de tiempo
              schema:
                type: number
            Content-Type:
              description: 'Formato de mensajería de la API. Ejemplo: application/json.'
              schema:
                type: string
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 502
                title: Bad Gateway
                errors:
                  - code: SP502
                    detail: El mensaje de respuesta recibido del servidor es inválido
        '503':
          description: Servicio no disponible.
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlación usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
            RateLimit-Limit:
              description: Límite de solicitudes por intervalo de tiempo
              schema:
                type: number
            Content-Type:
              description: 'Formato de mensajería de la API. Ejemplo: application/json.'
              schema:
                type: string
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 503
                title: Service Unavailable
                errors:
                  - code: SP503
                    detail: >-
                      Por problemas tecnicos su transaccion no pudo atenderse en
                      estos momentos, por favor intente mas tarde
        '504':
          description: Tiempo de respuesta del proveedor del servicio excedido.
          headers:
            Message-Id:
              description: >-
                Identificador del mensaje o de correlación usado para la
                trazabilidad de los llamados a las APIs.
              schema:
                type: string
            RateLimit-Limit:
              description: Límite de solicitudes por intervalo de tiempo
              schema:
                type: number
            Content-Type:
              description: 'Formato de mensajería de la API. Ejemplo: application/json.'
              schema:
                type: string
            API-Version:
              description: 'Version de la API. Ejemplo: 1.0.0.'
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/failure'
              example:
                meta:
                  _messageId: c4e6bd04-5149-11e7-b114-b2f933d5fe68
                  _requestDateTime: 2017-01-24T05:00:00.000Z
                  _applicationId: acxff62e-6f12-42de-9012-3e7304418abd
                status: 504
                title: Gateway Timeout
                errors:
                  - code: SP504
                    detail: El proveedor no respondió en tiempo esperado
      security:
        - clientSecret: []
          clientId: []
      x-codegen-request-body-name: requestBody
      tags:
        - Example Tag1
  /health:
    head:
      summary: Metodo que permite monitorear la API
      operationId: healthOperation
      responses:
        '200':
          description: Respuesta exitosa.
          x-ibm-languages:
            description:
              en: Successful response.
      security:
        - clientId: []
          clientSecret: []
      tags:
        - Monitoring
components:
  schemas:
    examplePath1Request:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - customer
          properties:
            customer:
              $ref: '#/components/schemas/customer'
    identification:
      type: object
      description: Información que relaciona la cuenta vinculada por el cliente
      required:
        - relationshipId
      properties:
        relationshipId:
          type: string
          description: >-
            identificador de la relacion de autorizacion establecida entre el
            tercero y el cliente para un producto específico
          minLength: 1
          maxLength: 33
          example: F1E4F933826EE5FF33
    examplePath1Response:
      type: object
      required:
        - meta
        - data
      properties:
        meta:
          $ref: '#/components/schemas/meta'
        data:
          type: object
          required:
            - message
          properties:
            customerId:
              type: string
              description: Identificador único del cliente registrado
              minLength: 10
              maxLength: 150
              example: "1093456378"
    customer:
      type: object
      description: Datos de cliente
      required:
        - identification
      properties:
        identification:
          $ref: '#/components/schemas/identification'
        fullName:
          type: string
          maxLength: 200
          example: Juan Martin Maya Echeverry
          description: Nombre completo del cliente
    meta:
      required:
        - _applicationId
        - _messageId
        - _requestDateTime
      type: object
      properties:
        _messageId:
          type: string
          example: 56d6adc5-b25a-4d75-a663-56a62bad4982
        _requestDateTime:
          type: string
          format: date-time
          example: 2016-06-23T16:07:21.205Z
        _applicationId:
          type: string
          example: acxff62e-6f12-42de-9012-3e7304418abd
      description: Datos de trazabilidad e informacion técnica del mensaje.
    failure:
      required:
        - errors
        - meta
      type: object
      properties:
        meta:
          $ref: '#/components/schemas/meta'
        status:
          type: number
          description: >-
            Codigo de estado HTTP (status code) asociado al mensaje de error de
            la respuesta del llamado a la API.
          example: 404
        title:
          type: string
          description: >-
            Titulo asociado al codigo de estado HTTP (status code) asociado al
            mensaje de error de la respuesta del llamado a la API.
          example: Not Found
        errors:
          type: array
          description: Lista de errores detectados
          items:
            $ref: '#/components/schemas/error'
      description: Mensaje de respuesta cuando ocurre un error.
    error:
      required:
        - code
        - detail
      type: object
      properties:
        code:
          type: string
          description: An application-specific error code, expressed as a string value.
          example: BP404
        detail:
          type: string
          description: >-
            A human-readable explanation specific to this occurrence of the
            problem.
          example: Requested resource could not be found
  securitySchemes:
    clientId:
      type: apiKey
      in: header
      name: Client-Id
      x-key-type: client_id
    clientSecret:
      type: apiKey
      in: header
      name: Client-Secret
      x-key-type: client_secret
tags:
  - name: Monitoring
    description: Operaciones para realizar el monitoreo de la API
  - name: Example Tag1
    description: >-
      Descripción de Subdominio o Recurso en común que de cierta forma permite agrupar operaciones (paths).
